"""Generate a route-package skeleton: `rynmesh/<name>_routes.py` + its test.

    python scripts/new_route_package.py <name> [--dest DIR]

Read `docs/ROUTE_PACKAGES.md` before running this — it documents the
conventions the generated skeleton follows (the installer signature,
`app.state` wiring, supervised workers, `/api/local` routing, error
handling). `docs/VERSIONED_RECORDS.md` documents the versioned-record
convention the generated store follows.

Writes exactly two files under `--dest` (default: this repo's root) and
prints their paths. Refuses to run — writing nothing — if `<name>` is not a
lowercase identifier or if either target file already exists.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

#: Lowercase identifier only: this becomes a Python module name, an
#: `app.state` attribute, a background-worker name, and a URL path segment,
#: so anything a bit more permissive (dashes, dots, mixed case) would break
#: one of those uses silently instead of failing here.
NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_]{1,30}$")

ROUTES_TEMPLATE = '''"""FastAPI routes for the {name} package.

Generated by `scripts/new_route_package.py`. Read `docs/ROUTE_PACKAGES.md`
before extending this file -- it documents the conventions every route
package in this repo follows (installer signature, `app.state` wiring,
supervised workers, `/api/local` vs `/api/peer` routing, and error
handling). `docs/VERSIONED_RECORDS.md` documents the versioned-record
convention `{Name}Store` follows below.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from fastapi import Request

from rynmesh import atomic_io
from rynmesh.background_workers import (
    BackgroundWorkerRegistry,
    BackgroundWorkerSpec,
    BackoffPolicy,
    WorkerRunResult,
)

# Bump when the on-disk shape of `{Name}Store`'s record changes; see
# docs/VERSIONED_RECORDS.md for the migrate-forward convention this
# constant anchors.
STATE_VERSION = 1

WORKER_NAME = "{name}.tick"

# `BackgroundWorkerSpec.policy` has no ready-made flat-interval constructor
# in this repo's `background_workers.py`, so a flat interval is built by
# hand: busy and idle delays are equal, and idle_multiplier=1.0 keeps the
# idle delay from ever growing past it. Swap for a real busy/idle/error
# split once this worker does real work.
TICK_POLICY = BackoffPolicy(
    busy_delay_s=60.0,
    idle_initial_s=60.0,
    idle_multiplier=1.0,
    idle_max_s=60.0,
    error_multiplier=2.0,
    error_max_s=300.0,
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


class {Name}Store:
    """One versioned record at ``home / "{name}" / "state.json"``.

    Every record carries a ``version`` field and is migrated forward at
    load time -- see docs/VERSIONED_RECORDS.md. Version 1 is the first
    shape, so ``_migrate`` is a documented no-op today: it exists so the
    next version bump has a single place to land, not because it does
    anything yet.
    """

    VERSION = STATE_VERSION

    def __init__(self, home: str | Path) -> None:
        self.home = Path(home)
        self.path = self.home / "{name}" / "state.json"
        self._record = self._load()

    def _load(self) -> dict[str, Any]:
        default: dict[str, Any] = {{"version": self.VERSION, "updated_at": ""}}
        record = atomic_io.read_json(self.path, default=default)
        if not isinstance(record, dict):
            record = default
        return self._migrate(record)

    def _migrate(self, record: dict[str, Any]) -> dict[str, Any]:
        """Forward-only migration hook; a no-op while VERSION stays 1.

        When a future version changes the record's shape: read the old
        record, call ``atomic_io.migration_backup(self.path)`` *before*
        writing the upgraded record, then add the new fields here. Unknown
        fields on an already-current record are preserved, never dropped.
        """
        if record.get("version") == self.VERSION:
            return record
        return {{"version": self.VERSION, "updated_at": ""}}

    def touch(self) -> dict[str, Any]:
        """Update ``updated_at``, write durably, and return a copy of the record."""
        self._record = dict(self._record)
        self._record["version"] = self.VERSION
        self._record["updated_at"] = _now()
        atomic_io.atomic_write_json(self.path, self._record, indent=2, sort_keys=True)
        return dict(self._record)

    def snapshot(self) -> dict[str, Any]:
        return dict(self._record)


def _tick(store: {Name}Store) -> Callable[[], WorkerRunResult]:
    """Build the placeholder worker body -- replace with real polling/work.

    Returning ``WorkerRunResult(activity=False)`` always reports "idle" to
    the supervisor, so this worker backs off to ``TICK_POLICY.idle_max_s``
    and stays there. A real body should report ``activity=True`` whenever
    it did something, so the busy/idle backoff behaves as intended.
    """

    def run_once() -> WorkerRunResult:
        return WorkerRunResult(activity=False)

    return run_once


def install_{name}(
    app: Any,
    *,
    store: Any,
    home: str | Path,
    workers: BackgroundWorkerRegistry,
    local_control: Callable[[Request], None] | None = None,
) -> {Name}Store:
    """Install the {name} package: state, one supervised worker, its status route.

    ``home`` is the configured node home; the *store's* home wins when they
    disagree (see docs/ROUTE_PACKAGES.md, and ``install_mailbox`` in
    rynmesh/mailbox_routes.py for why: the store owns the identity this
    package's files belong next to).
    """

    resolved_home = Path(getattr(store, "home", None) or home)
    state = {Name}Store(resolved_home)
    app.state.{name} = state
    app.state.{name}_error = ""

    workers.register(
        BackgroundWorkerSpec(
            name=WORKER_NAME,
            run_once=_tick(state),
            policy=TICK_POLICY,
            error_sink=lambda value: setattr(app.state, "{name}_error", value),
        ),
        replace=True,  # an installer must be safe to run twice (re-installed routes, tests)
    )

    @app.get("/api/local/{name}/status")
    def local_{name}_status(request: Request) -> dict[str, Any]:
        # /api/local is gated by the node-auth middleware; this mirrors the
        # per-route re-check every other package's local routes do on top
        # of it (see docs/ROUTE_PACKAGES.md).
        if local_control is not None:
            local_control(request)
        record = state.snapshot()
        return {{
            "version": record.get("version"),
            "updated_at": record.get("updated_at"),
            "worker": workers.status().get(WORKER_NAME),
        }}

    return state


__all__ = [
    "STATE_VERSION",
    "TICK_POLICY",
    "WORKER_NAME",
    "{Name}Store",
    "install_{name}",
]
'''

TEST_TEMPLATE = '''"""Tests for the generated `{name}` route package.

Generated by `scripts/new_route_package.py`; see docs/ROUTE_PACKAGES.md for
the conventions this exercises.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

from fastapi import FastAPI
from fastapi.testclient import TestClient

{rynmesh_imports}


class _StubStore:
    """Minimal stand-in for `RynmeshStore`: only `home` is read by the installer."""

    def __init__(self, home: Path) -> None:
        self.home = home


def _install(tmp_path: Path, app: FastAPI, workers: BackgroundWorkerRegistry):
    store = _StubStore(tmp_path)
    return install_{name}(app, store=store, home=tmp_path, workers=workers)


def test_install_sets_app_state_and_registers_worker(tmp_path: Path) -> None:
    app = FastAPI()
    workers = BackgroundWorkerRegistry()
    state = _install(tmp_path, app, workers)

    assert app.state.{name} is state
    specs = {{spec.name: spec for spec in workers.specs()}}
    assert WORKER_NAME in specs
    assert specs[WORKER_NAME].policy == TICK_POLICY


def test_install_twice_does_not_raise(tmp_path: Path) -> None:
    app = FastAPI()
    workers = BackgroundWorkerRegistry()
    _install(tmp_path, app, workers)
    _install(tmp_path, app, workers)  # installer must be safe to run twice

    assert len(workers.specs()) == 1


def test_status_route_returns_documented_shape(tmp_path: Path) -> None:
    app = FastAPI()
    workers = BackgroundWorkerRegistry()
    _install(tmp_path, app, workers)
    client = TestClient(app)

    response = client.get("/api/local/{name}/status")

    assert response.status_code == 200
    body = response.json()
    assert set(body) == {{"version", "updated_at", "worker"}}
    assert body["version"] == 1


def test_status_route_calls_local_control(tmp_path: Path) -> None:
    app = FastAPI()
    workers = BackgroundWorkerRegistry()
    store = _StubStore(tmp_path)
    calls = []
    install_{name}(
        app, store=store, home=tmp_path, workers=workers,
        local_control=lambda request: calls.append(request),
    )
    client = TestClient(app)

    client.get("/api/local/{name}/status")

    assert len(calls) == 1


def test_store_round_trips_a_0600_record(tmp_path: Path) -> None:
    app = FastAPI()
    workers = BackgroundWorkerRegistry()
    state = _install(tmp_path, app, workers)

    written = state.touch()

    assert written["version"] == 1
    path = tmp_path / "{name}" / "state.json"
    assert path.is_file()
    if os.name == "posix":
        mode = stat.S_IMODE(path.stat().st_mode)
        assert mode == 0o600
'''


def _pascal_case(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_") if part)


def _test_import_block(name: str) -> str:
    """Two `rynmesh.*` import lines, alphabetized as ruff's isort check wants.

    Which of `rynmesh.background_workers` or `rynmesh.<name>_routes` sorts
    first depends on `<name>` (e.g. "assistant" sorts before "background",
    "library" does not), so this is computed rather than hardcoded.
    """
    workers_import = "from rynmesh.background_workers import BackgroundWorkerRegistry"
    routes_import = "from rynmesh.{name}_routes import TICK_POLICY, WORKER_NAME, install_{name}".format(
        name=name,
    )
    return "\n".join(sorted([workers_import, routes_import]))


def generate(name: str, dest: Path) -> tuple[Path, Path]:
    """Write the two-file skeleton under `dest`; return their paths.

    Both target files are checked for existence *before* anything is
    written, so a rejected name or an existing file leaves `dest` untouched.
    """

    if not NAME_PATTERN.match(name):
        raise ValueError(
            "name must match ^[a-z][a-z0-9_]{1,30}$ "
            "(lowercase letters, digits, underscores; must start with a letter)"
        )
    dest = Path(dest).resolve()
    routes_path = dest / "rynmesh" / f"{name}_routes.py"
    test_path = dest / "tests" / f"test_{name}_routes.py"
    for path in (routes_path, test_path):
        if path.exists():
            raise FileExistsError(f"refusing to overwrite existing file: {path.name}")

    class_name = _pascal_case(name)
    routes_source = ROUTES_TEMPLATE.format(name=name, Name=class_name)
    test_source = TEST_TEMPLATE.format(
        name=name, Name=class_name, rynmesh_imports=_test_import_block(name),
    )

    routes_path.parent.mkdir(parents=True, exist_ok=True)
    test_path.parent.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    try:
        routes_path.write_text(routes_source, encoding="utf-8")
        written.append(routes_path)
        test_path.write_text(test_source, encoding="utf-8")
        written.append(test_path)
    except BaseException:
        # Never leave an orphaned first file behind for a retry to trip over
        # with a `FileExistsError` that doesn't explain it's a leftover.
        for path in written:
            path.unlink(missing_ok=True)
        raise
    return routes_path, test_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name", help="lowercase package identifier, e.g. first_run")
    parser.add_argument(
        "--dest",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="destination repo root (default: this repo)",
    )
    args = parser.parse_args(argv)
    try:
        routes_path, test_path = generate(args.name, args.dest)
    except (ValueError, FileExistsError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(routes_path)
    print(test_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
